version: '3'
services:
  nginx:
    image: 'nginx'
    restart: always
    container_name: nginx
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=1qazZAQ!
      - TZ=Asia/Shanghai