version: "3"
services:
  kong-database:
    image: postgres:9.6
    restart: always
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - ~/storage/data/kong/postgresql/data:/var/lib/postgresql/data
  kong-database-bootstrap:
    image: kong:latest
    container_name: kong-database-bootstrap
    environment: 
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    depends_on:
      - kong-database   
  kong-gateway:
    image: zlzforever/kong:latest
    restart: always
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    command: kong docker-start
    volumes:
      - ~/github/my-docker/docker-compose/kong/kong.conf:/etc/kong/kong.conf
      - ~/storage/data/kong/logs:/usr/local/kong/logs
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga
    restart: always
    container_name: konga
    ports:
      - 1337:1337
    depends_on:
      - kong-gateway 
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=Abcd.abcd.654321
      - TZ=Asia/Shanghai 